version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "your_root_password"
      MYSQL_DATABASE: "db_name"
      MYSQL_USER: "1234"
      MYSQL_PASSWORD: "7890"
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mynetwork

  test-app:
    build: .
    command: ["python", "test_app.py"]
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
